-- MySQL Script generated by MySQL Workbench
-- 04/27/16 18:27:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dms` DEFAULT CHARACTER SET utf8 ;
USE `dms` ;

-- -----------------------------------------------------
-- Table `dms`.`KorisnikTip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`KorisnikTip` (
  `KorisnikTipID` INT NOT NULL AUTO_INCREMENT,
  `KorisnikTipNaziv` NVARCHAR(200) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`KorisnikTipID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`KorisnikPozicija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`KorisnikPozicija` (
  `KorisnikPozicijaID` INT NOT NULL AUTO_INCREMENT,
  `KorisnikPozicijaNaziv` NVARCHAR(200) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`KorisnikPozicijaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Korisnik` (
  `KorisnikID` INT NOT NULL AUTO_INCREMENT,
  `Ime` NVARCHAR(50) NULL,
  `Prezime` NVARCHAR(50) NULL,
  `Adresa` NVARCHAR(200) NULL,
  `DatumRodjenja` DATETIME NULL,
  `Username` NVARCHAR(200) NULL,
  `Password` NVARCHAR(300) NULL,
  `KorisnikTipID` INT NOT NULL,
  `KorisnikPozicijaID` INT NOT NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`KorisnikID`),
  INDEX `fk_Korisnik_KorisnikTip_idx` (`KorisnikTipID` ASC),
  INDEX `fk_Korisnik_KorisnikPozicija1_idx` (`KorisnikPozicijaID` ASC),
  CONSTRAINT `fk_Korisnik_KorisnikTip`
    FOREIGN KEY (`KorisnikTipID`)
    REFERENCES `dms`.`KorisnikTip` (`KorisnikTipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik_KorisnikPozicija1`
    FOREIGN KEY (`KorisnikPozicijaID`)
    REFERENCES `dms`.`KorisnikPozicija` (`KorisnikPozicijaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Grupa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Grupa` (
  `GrupaID` INT NOT NULL AUTO_INCREMENT,
  `GrupaNaziv` NVARCHAR(300) NULL,
  `OdgovorniKorisnikID` INT NOT NULL,
  `DatumKreiranja` DATETIME NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`GrupaID`),
  INDEX `fk_Grupa_Korisnik1_idx` (`OdgovorniKorisnikID` ASC),
  CONSTRAINT `fk_Grupa_Korisnik1`
    FOREIGN KEY (`OdgovorniKorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`GrupaXKorisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`GrupaXKorisnik` (
  `GrupaXKorisnikID` INT NOT NULL AUTO_INCREMENT,
  `GrupaID` INT NOT NULL,
  `KorisnikID` INT NOT NULL,
  `DatumZadnjeIzmjene` DATETIME NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`GrupaXKorisnikID`),
  INDEX `fk_GrupaXKorisnik_Grupa1_idx` (`GrupaID` ASC),
  INDEX `fk_GrupaXKorisnik_Korisnik1_idx` (`KorisnikID` ASC),
  CONSTRAINT `fk_GrupaXKorisnik_Grupa1`
    FOREIGN KEY (`GrupaID`)
    REFERENCES `dms`.`Grupa` (`GrupaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GrupaXKorisnik_Korisnik1`
    FOREIGN KEY (`KorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Folder` (
  `FolderID` INT NOT NULL AUTO_INCREMENT,
  `FolderNaziv` NVARCHAR(100) NULL,
  `KreiraoKorisnikID` INT NOT NULL,
  `RoditeljFolderID` INT NOT NULL,
  `Aktivan` BIT NULL,
  PRIMARY KEY (`FolderID`),
  INDEX `fk_Folder_Korisnik1_idx` (`KreiraoKorisnikID` ASC),
  INDEX `fk_Folder_Folder1_idx` (`RoditeljFolderID` ASC),
  CONSTRAINT `fk_Folder_Korisnik1`
    FOREIGN KEY (`KreiraoKorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Folder_Folder1`
    FOREIGN KEY (`RoditeljFolderID`)
    REFERENCES `dms`.`Folder` (`FolderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Dokument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Dokument` (
  `DokumentID` INT NOT NULL AUTO_INCREMENT,
  `FolderID` INT NOT NULL,
  `Dokument` NVARCHAR(200) NULL,
  `Ekstenzija` NVARCHAR(15) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`DokumentID`),
  INDEX `fk_Dokument_Folder1_idx` (`FolderID` ASC),
  CONSTRAINT `fk_Dokument_Folder1`
    FOREIGN KEY (`FolderID`)
    REFERENCES `dms`.`Folder` (`FolderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`DokumentVerzijaStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`DokumentVerzijaStatus` (
  `DokumentVerzijaStatusID` INT NOT NULL AUTO_INCREMENT,
  `DokumentVerzijaStatusNaziv` NVARCHAR(100) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`DokumentVerzijaStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`DokumentVerzija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`DokumentVerzija` (
  `DokumentVerzijaID` INT NOT NULL AUTO_INCREMENT,
  `DokumentID` INT NOT NULL,
  `PostavioKorisnikID` INT NOT NULL,
  `DokumentVerzijaStatusID` INT NOT NULL,
  `Sadrzaj` BLOB NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`DokumentVerzijaID`),
  INDEX `fk_DokumentVerzija_Dokument1_idx` (`DokumentID` ASC),
  INDEX `fk_DokumentVerzija_Korisnik1_idx` (`PostavioKorisnikID` ASC),
  INDEX `fk_DokumentVerzija_DokumentVerzijaStatus1_idx` (`DokumentVerzijaStatusID` ASC),
  CONSTRAINT `fk_DokumentVerzija_Dokument1`
    FOREIGN KEY (`DokumentID`)
    REFERENCES `dms`.`Dokument` (`DokumentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DokumentVerzija_Korisnik1`
    FOREIGN KEY (`PostavioKorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DokumentVerzija_DokumentVerzijaStatus1`
    FOREIGN KEY (`DokumentVerzijaStatusID`)
    REFERENCES `dms`.`DokumentVerzijaStatus` (`DokumentVerzijaStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Komentar` (
  `KomentarID` INT NOT NULL AUTO_INCREMENT,
  `KorisnikID` INT NOT NULL,
  `DokumentVerzijaID` INT NOT NULL,
  `Komentar` NVARCHAR(400) NULL,
  `DatumVrijemeKomentara` DATETIME NULL,
  `Aktivan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KomentarID`),
  INDEX `fk_Komentar_DokumentVerzija1_idx` (`DokumentVerzijaID` ASC),
  INDEX `fk_Komentar_Korisnik1_idx` (`KorisnikID` ASC),
  CONSTRAINT `fk_Komentar_DokumentVerzija1`
    FOREIGN KEY (`DokumentVerzijaID`)
    REFERENCES `dms`.`DokumentVerzija` (`DokumentVerzijaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Komentar_Korisnik1`
    FOREIGN KEY (`KorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`ZahtjevTip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`ZahtjevTip` (
  `ZahtjevTipID` INT NOT NULL AUTO_INCREMENT,
  `ZahtjevTipNaziv` NVARCHAR(100) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`ZahtjevTipID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`ZahtjevStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`ZahtjevStatus` (
  `ZahjtevStatusID` INT NOT NULL AUTO_INCREMENT,
  `ZahjtevStatusNaziv` NVARCHAR(100) NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`ZahjtevStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`Zahtjev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`Zahtjev` (
  `ZahtjevID` INT NOT NULL AUTO_INCREMENT,
  `DatumVrijemeKreiranja` DATETIME NULL,
  `KreiraoKorisnikID` INT NOT NULL,
  `UpucenoKorisnikID` INT NOT NULL,
  `ZahtjevTipID` INT NOT NULL,
  `ZahtjevStatusID` INT NOT NULL,
  `DokumentVerzijaID` INT NOT NULL,
  `Aktivan` BIT NOT NULL,
  PRIMARY KEY (`ZahtjevID`),
  INDEX `fk_Zahtjev_Korisnik1_idx` (`KreiraoKorisnikID` ASC),
  INDEX `fk_Zahtjev_Korisnik2_idx` (`UpucenoKorisnikID` ASC),
  INDEX `fk_Zahtjev_ZahtjevTip1_idx` (`ZahtjevTipID` ASC),
  INDEX `fk_Zahtjev_ZahjtevStatus1_idx` (`ZahtjevStatusID` ASC),
  INDEX `fk_Zahtjev_DokumentVerzija1_idx` (`DokumentVerzijaID` ASC),
  CONSTRAINT `fk_Zahtjev_Korisnik1`
    FOREIGN KEY (`KreiraoKorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zahtjev_Korisnik2`
    FOREIGN KEY (`UpucenoKorisnikID`)
    REFERENCES `dms`.`Korisnik` (`KorisnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zahtjev_ZahtjevTip1`
    FOREIGN KEY (`ZahtjevTipID`)
    REFERENCES `dms`.`ZahtjevTip` (`ZahtjevTipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zahtjev_ZahjtevStatus1`
    FOREIGN KEY (`ZahtjevStatusID`)
    REFERENCES `dms`.`ZahtjevStatus` (`ZahjtevStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zahtjev_DokumentVerzija1`
    FOREIGN KEY (`DokumentVerzijaID`)
    REFERENCES `dms`.`DokumentVerzija` (`DokumentVerzijaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`FolderXGrupa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`FolderXGrupa` (
  `FolderXGrupaID` INT NOT NULL,
  `GrupaID` INT NOT NULL,
  `FolderID` INT NOT NULL,
  `PravoSkidanja` BIT NULL,
  `PravoDodavanja` BIT NULL,
  `Aktivan` BIT NULL,
  PRIMARY KEY (`FolderXGrupaID`),
  INDEX `fk_FolderXGrupa_Grupa1_idx` (`GrupaID` ASC),
  INDEX `fk_FolderXGrupa_Folder1_idx` (`FolderID` ASC),
  CONSTRAINT `fk_FolderXGrupa_Grupa1`
    FOREIGN KEY (`GrupaID`)
    REFERENCES `dms`.`Grupa` (`GrupaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FolderXGrupa_Folder1`
    FOREIGN KEY (`FolderID`)
    REFERENCES `dms`.`Folder` (`FolderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


GRANT ALL PRIVILEGES ON *.* TO 'dmsuser'@'%' IDENTIFIED BY PASSWORD 'dmsuser123' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `dms`.* TO 'dmsuser'@'%';
